simulation:
  simulation_frequency: 1000 # Frequency of physics simulation updates (Hz)
  duration: 90.0 # Total duration of the simulation (seconds)

quadrotor:
  mass: 1.3 # Mass of the quadrotor (kg)
  gravity: 9.81 # Gravitational acceleration (m/s^2)
  drag_coefficient: 0.000 # Aerodynamic drag coefficient
  # Inertia matrix [Ixx, Ixy, Ixz, Iyx, Iyy, Iyz, Izx, Izy, Izz] (kg*m^2)
  inertia_matrix: [3.04e-3, 0.0, 0.0, 0.0, 4.55e-3, 0.0, 0.0, 0.0, 2.82e-3]

pid_controller:
  pos_gains: # PID gains for position control
    kp: [7.1, 7.1, 11.9] # Proportional gains [x, y, z]
    kd: [2.4, 2.4, 6.7] # Derivative gains [x, y, z]
    ki: [0.0, 0.0, 0.0] # Integral gains [x, y, z]
  att_gains: # PID gains for attitude control
    kp: [1.5, 1.5, 1.0] # Proportional gains [roll, pitch, yaw]
    kd: [0.13, 0.13, 0.1] # Derivative gains [roll, pitch, yaw]
    ki: [0.0, 0.0, 0.0] # Integral gains [roll, pitch, yaw]
  pos_max_int: [10.0, 10.0, 10.0] # Maximum integral error for position control [x, y, z]
  att_max_int: [0.5, 0.5, 0.5] # Maximum integral error for attitude control [roll, pitch, yaw]
